### ISSUE TITLE
Reference of `router` returned from `useRouter` is not preserved

### ISSUE THREAD

**Issue by raon0211** [scottrippey/next-router-mock#36]
The reference of `router` returned from `useRouter` is not preserved.
This differs from the actual behavior of Next.js, where the singleton router is returned from `useRouter` (thus preserving the reference).

The actual behavior of Next.js is that they make a [subscription](https://github.com/vercel/next.js/blob/canary/packages/next/client/index.tsx#L405) to the router's update and triggers [the re-render of the page](https://github.com/vercel/next.js/blob/ad997344893403948a70edb47b0d056658458e39/packages/next/client/index.tsx#L656). Since the props object is [created every time](https://github.com/vercel/next.js/blob/ad997344893403948a70edb47b0d056658458e39/packages/next/shared/lib/router/router.ts#L1475), the page component effectively re-renders every time.

In contrast, `next-router-mock` always creates [a new instance of the router](https://github.com/scottrippey/next-router-mock/blob/main/src/useMemoryRouter.tsx#L26). When using `useEffect` with `router` in the deps, this results in an infinite loop. (In actual next.js, the app functions as normal)

**Comment by scottrippey** [comment]
I'm currently on vacation without access to my computer, so I won't be able to test this until next week. But I have some questions in the meantime.

How confident are you that in Next, the `useRouter` reference doesn't change?
I intentionally added the "change the reference" behavior, based on what I thought Next was doing. I even added unit tests for this scenario.
Maybe the behavior has changed between Next versions?

One big reason I ask is because `router.query` could change between renders, but if you used just `router` in your dependencies, it wouldn't trigger the dependency change. Maybe Next doesn't care, but I'm pretty sure that's how it worked when I was testing it last.
I could definitely be wrong, but I want to make sure.

**Comment by scottrippey** [comment]
I created a sandbox to test this issue: https://codesandbox.io/s/test-next-router-reference-lqbn0i
What I'm seeing: whenever I call `router.push(...)`, the component re-renders, and the `useRouter()` hook returns a NEW reference each time the `router.query` changes.  When non-route-related changes occur (eg. `setState` is called), the router reference doesn't change.

This is what `next-router-mock` accurately reproduces.  So I think this behavior needs to stay as-is.

Please let me know if you can reproduce different behavior from Next, or perhaps if a different version of Next behaves differently.  Thanks!

**Comment by raon0211** [comment]
Sorry for the late reply.

You are indeed correct; I think since the page component usually unmounts after invoking `router.push` or `router.replace`, we did not encounter the problem of infinite rendering. 

It seems that having `router.replace` in the deps of useEffect is not an option because it also runs into infinite rerendering ([Codesandbox](https://codesandbox.io/s/test-next-router-reference-forked-7p830o?file=/pages/test/index.js)) and ESLint warns about the incorrect deps problem (I remember this is due to the notorious `this` in JS)

It might be better for us to create a fake Next.js app which unmounts the component when `router.pathname` changes. I think this matches the actual behavior of Next.js.

Thanks for looking deeply into the problem and helping us 👍
